version: 2.1


jobs:
  build:
    working_directory: ~/acara-events-backend
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restorce_cache:
          key: acara-events-backend-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: acara-events-backend-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
        path: target/surefire-reports
      - store_artifacts:
          path: target/acara-events-backend-0.0.1-SNAPSHOT.jar
