version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.2

  jobs:
    build:
      docker:
        - image: circleci/openjdk:11.0.3-jdk-stretch
      steps:
        - codecov/upload:
            file: {{ coverage_report_filepath }}

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
